/**
 * Markdown formatting utilities for SmartTable component
 */

import type { BusinessIdea } from "@/types/business-idea";

/**
 * Format overall score analysis as markdown
 */
export const formatOverallScoreMarkdown = (idea: BusinessIdea): string => {
  const scores = idea.scores;
  const reasoning = idea.reasoning;
  
  return `# Overall Score Analysis

## Score: ${scores.overall ? `${scores.overall.toFixed(1)}/10` : 'Pending'}

### Reasoning
${reasoning.overall || 'Overall analysis is being generated...'}

## Score Breakdown

| Metric | Score | Description |
|--------|-------|-------------|
| **Disruption Potential** | ${scores.disruption ? `${scores.disruption.toFixed(1)}/10` : 'Pending'} | ${reasoning.disruption || 'Analysis pending...'} |
| **Market Potential** | ${scores.market ? `${scores.market.toFixed(1)}/10` : 'Pending'} | ${reasoning.market || 'Analysis pending...'} |
| **Technical Complexity** | ${scores.technical ? `${scores.technical.toFixed(1)}/10` : 'Pending'} | ${reasoning.technical || 'Analysis pending...'} |
| **Capital Intensity** | ${scores.capital ? `${scores.capital.toFixed(1)}/10` : 'Pending'} | ${reasoning.capital || 'Analysis pending...'} |
| **Blue Ocean Score** | ${scores.blueOcean ? `${scores.blueOcean.toFixed(1)}/10` : 'Pending'} | ${reasoning.blueOcean || 'Analysis pending...'} |

## Business Details

**Title:** ${idea.title}

**Description:** ${idea.description}

**Business Model:** ${idea.businessModel}

**Execution Mode:** ${idea.executionMode || 'Not specified'}
`;
};

/**
 * Format critical analysis as markdown
 */
export const formatCriticalAnalysisMarkdown = (idea: BusinessIdea): string => {
  return `# Critical Analysis

## ${idea.title}

### Analysis
${idea.criticalAnalysis || 'Critical analysis is being generated by the Business Critic Agent...'}

### Overall Score
${idea.scores.overall ? `**${idea.scores.overall.toFixed(1)}/10**` : 'Score pending...'}

${idea.reasoning.overall ? `#### Reasoning\n${idea.reasoning.overall}` : ''}

### Key Considerations
- **Market Potential:** ${idea.scores.market ? `${idea.scores.market}/10` : 'Pending'}
- **Technical Complexity:** ${idea.scores.technical ? `${idea.scores.technical}/10` : 'Pending'}
- **Capital Requirements:** ${idea.scores.capital ? `${idea.scores.capital}/10` : 'Pending'}
`;
};

/**
 * Format competitor analysis as markdown
 */
export const formatCompetitorAnalysisMarkdown = (idea: BusinessIdea): string => {
  return `# Competitor Analysis

## ${idea.title}

### Market Analysis
${idea.competitorAnalysis || 'Competitor analysis is being performed by the Competitor Agent...'}

### Blue Ocean Score
${idea.scores.blueOcean ? `**${idea.scores.blueOcean.toFixed(1)}/10**` : 'Score pending...'}

${idea.reasoning.blueOcean ? `#### Blue Ocean Reasoning\n${idea.reasoning.blueOcean}` : ''}

### Market Positioning
- **Disruption Potential:** ${idea.scores.disruption ? `${idea.scores.disruption}/10` : 'Pending'}
- **Market Saturation:** ${idea.scores.blueOcean ? (10 - idea.scores.blueOcean).toFixed(1) : 'N/A'}/10
`;
};